### ISSUE TITLE
phpbb update broke the extension

### ISSUE THREAD

**Issue by lmclarke** [rootslinux/phpbb-discord-notifications#35]
The extension appears to have been made non-functional by the latest phpbb update.

Attempting to make a new post:
`{"message": "Cannot send an empty message", "code": 50006}[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 1847: Cannot modify header information - headers already sent by (output started at [ROOT]/ext/roots/discordnotifications/notification_service.php:328)`

The message isn't empty.

**Comment by efinst0rm** [comment]
phpBB had nothing to do with this extension breaking. Discord change their API. The fix can be found here. https://github.com/rootslinux/phpbb-discord-notifications/issues/33
